export const ESCORTS_LIST_REQUEST = 'ESCORTS_LIST_REQUEST';
export const ESCORTS_LIST_SUCCESS = 'ESCORTS_LIST_SUCCESS';
export const ESCORTS_LIST_FAIL = 'ESCORTS_LIST_FAIL';

export const ESCORT_REGISTER_REQUEST = 'ESCORT_REGISTER_REQUEST';
export const ESCORT_REGISTER_SUCCESS = 'ESCORT_REGISTER_SUCCESS';
export const ESCORT_REGISTER_FAIL = 'ESCORT_REGISTER_FAIL';