export const USER_SIGIN_REQUEST = 'USER_SIGIN_REQUEST';
export const USER_SIGIN_SUCCESS = 'USER_SIGIN_SUCCESS';
export const USER_SIGIN_FAIL = 'USER_SIGIN_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';